/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

/**
 *
 * @author yostin
 */
public class PnlVehicle extends javax.swing.JPanel {

    /**
     * Creates new form PnlVehicle
     */
    public PnlVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);
        jPanel2.add(jSpinner1);
        jSpinner1.setBounds(400, 30, 60, 20);

        jFormattedTextField1.setText("jFormattedTextField1");
        jPanel2.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(110, 190, 110, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(110, 230, 60, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(110, 270, 60, 20);
        jPanel2.add(jSpinner2);
        jSpinner2.setBounds(400, 60, 60, 20);
        jPanel2.add(jSpinner3);
        jSpinner3.setBounds(110, 150, 70, 20);

        jToggleButton1.setText("jToggleButton1");
        jPanel2.add(jToggleButton1);
        jToggleButton1.setBounds(400, 140, 105, 23);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox5);
        jComboBox5.setBounds(400, 180, 57, 20);

        jLabel1.setText("Marca");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 29, 14);

        jLabel2.setText("Modelo");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 70, 34, 14);

        jLabel3.setText("Estilo");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 110, 25, 14);

        jLabel4.setText("Año");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 150, 19, 14);

        jLabel5.setText("vin");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 190, 14, 14);

        jLabel6.setText("Color Exterior");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 230, 66, 14);

        jLabel7.setText("Color Interior");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 270, 64, 14);

        jLabel8.setText("Millas Recorridas");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(260, 30, 80, 14);

        jLabel9.setText("Precio");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(260, 70, 29, 14);

        jLabel10.setText("Tipo de Transmicion");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(260, 100, 100, 20);

        jLabel11.setText("Engine");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(260, 140, 32, 14);

        jLabel12.setText("Estado");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(260, 180, 40, 14);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox6);
        jComboBox6.setBounds(400, 100, 57, 20);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(110, 70, 70, 20);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(110, 30, 70, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(110, 110, 70, 20);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("jButton1");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
