/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author JADPA06
 */
public class PnlEditor extends javax.swing.JPanel {

    /**
     * Creates new form PnlEditor
     */
    public PnlEditor() {
        initComponents();
    }
    
    

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JLabel getLblLetters() {
        return lblLetters;
    }

    public void setLblLetters(JLabel lblLetters) {
        this.lblLetters = lblLetters;
    }

    public JLabel getLblLines() {
        return lblLines;
    }

    public void setLblLines(JLabel lblLines) {
        this.lblLines = lblLines;
    }

    public JLabel getLblWords() {
        return lblWords;
    }

    public void setLblWords(JLabel lblWords) {
        this.lblWords = lblWords;
    }

    public JTextArea getTxtaEditor() {
        return txtaEditor;
    }

    public void setTxtaEditor(JTextArea txtaEditor) {
        this.txtaEditor = txtaEditor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLines = new javax.swing.JLabel();
        lblWords = new javax.swing.JLabel();
        lblLetters = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaEditor = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblLines.setText("Lines:");
        jPanel1.add(lblLines);

        lblWords.setText("Words:");
        jPanel1.add(lblWords);

        lblLetters.setText("Letters:");
        jPanel1.add(lblLetters);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        txtaEditor.setColumns(20);
        txtaEditor.setRows(5);
        jScrollPane2.setViewportView(txtaEditor);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLetters;
    private javax.swing.JLabel lblLines;
    private javax.swing.JLabel lblWords;
    private javax.swing.JTextArea txtaEditor;
    // End of variables declaration//GEN-END:variables
}
